# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print:
    description: "A simple echo"
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Print a message
          command: echo << parameters.message >> 

jobs:
    one:
      docker:
          - image: circleci/ruby:2.4
      steps:
          - print:
              message: "one"
    

workflows:
    version: 2.1
    build:
        jobs:
            - one