# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print:
    description: "A simple echo"
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Print a message
          command: echo Hello << parameters.message >> 

jobs:
  build-image:
    docker:
        - image: circleci/ruby:2.4
    steps:
        - print:
            message: "one"
  

workflows:
  version: 2.1
  deploy-staging:
      jobs:
          - build-and-push-image:
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - deploy-test-env:
              requires:
                - build-and-push-image
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - deploy-to-staging:
              requires:
                - build-and-push-image
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - integration-tests:
              requires:
                - deploy-test-env
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - acceptance-tests:
              requires:
                - deploy-to-staging
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          