# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print:
    description: "A simple echo"
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Print a message
          command: echo Hello << parameters.message >> 

jobs:
  build-and-push-image:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "build and push"


  deploy-test-env:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "deploying test env"

  deploy-to-staging:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "deploying staging env"

  integration-tests:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - checkout
        - print:
            message: "running integration tests"

        - run:
              name: Run integration tests
              command: |
                  bash ./.circleci/scripts/integration_test.sh
  acceptance-tests:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - checkout
        - print:
            message: "running acceptance tests"

        - run:
              name: Run integration tests
              command: |
                  bash ./.circleci/scripts/acceptance_test.sh  

workflows:
  version: 2.1
  deploy-staging:
      jobs:
          - build-and-push-image:
              filters:
                tags:
                  only: /^staging$/check
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - deploy-test-env:
              requires:
                - build-and-push-image
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - deploy-to-staging:check
              requires:
                - build-and-push-image
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - integration-tests:check
              requires:
                - deploy-test-env
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          - acceptance-tests:
              requires:
                - deploy-to-staging
              filters:
                tags:
                  only: /^staging$/
                # Exclude commits on all branches
                branches:
                  ignore: /.*/
          